### ISSUE TITLE
image not displaying

### ISSUE THREAD

**Issue by Dan-himself** [raspberrypilearning/hardware-guide#1]
In quickstart > 2. Monitors - image of monitor isn't displaying.

![image](https://cloud.githubusercontent.com/assets/18287886/15249792/73719a7a-1919-11e6-8fbd-62a63a192f7d.png)

**Comment by LornaLynch** [comment]
I just checked the image folder, and the monitor image isn't there yet, hence the problem. @MarcScott, do you have it?
